import "dotenv/config";

const NUMBER_OF_PARTITIONS_WORDS = process.env.NUMBER_OF_PARTITIONS_WORDS || 1;
const WORDS_CONSUMER_GROUP =
  process.env.WORDS_CONSUMER_GROUP ?? "WORDS_CONSUMER_GROUP";
const KAFKA_WORDS_TOPIC = process.env.KAFKA_WORDS_TOPIC ?? "KAFKA_WORDS_TOPIC";

const NUMBER_OF_PARTITIONS_HTMLS = process.env.NUMBER_OF_PARTITIONS_HTMLS ?? 1;
const HTMLS_CONSUMER_GROUP =
  process.env.HTMLS_CONSUMER_GROUP ?? "HTMLS_CONSUMER_GROUP";
const KAFKA_HTMLS_TOPIC = process.env.KAFKA_HTMLS_TOPIC ?? "KAFKA_HTMLS_TOPIC";

const NUMBER_OF_PARTITIONS_URLS = process.env.NUMBER_OF_PARTITIONS_URLS ?? 1;
const URLS_CONSUMER_GROUP =
  process.env.URLS_CONSUMER_GROUP ?? "URLS_CONSUMER_GROUP";
const KAFKA_URLS_TOPIC = process.env.KAFKA_URLS_TOPIC ?? "KAFKA_URLS_TOPIC";

const KAFKA_PERSIST_DB_TOPIC =
  process.env.KAFKA_PERSIST_DB_TOPIC ?? "KAFKA_PERSIST_DB_TOPIC";
const PERSIST_DB_CONSUMER_GROUP =
  process.env.PERSIST_DB_CONSUMER_GROUP ?? "PERSIST_DB_CONSUMER_GROUP";
const NUMBER_OF_PARTITIONS_PERSIST_DB =
  process.env.NUMBER_OF_PARTITIONS_PERSIST_DB ?? 1;

const REDIS_SERVER_HOST = process.env.REDIS_SERVER_HOST ?? "redis";
const REDIS_SERVER_PORT = process.env.REDIS_SERVER_PORT ?? 6379;

const KAFKA_BROKER_HOST = process.env.KAFKA_BROKER_HOST;
const KAFKA_BROKER_PORT = process.env.KAFKA_BROKER_PORT;
const KAFKA_BROKER_URL = process.env.KAFKA_BROKER_URL;

const MONGODB_DATABASE = process.env.MONGODB_DATABASE;
const MONGODB_HOST = process.env.MONGODB_HOST;
const MONGODB_PORT = process.env.MONGODB_PORT;

const LIMIT_URLS_NUMBER = process.env.LIMIT_URLS_NUMBER;

export {
  HTMLS_CONSUMER_GROUP,
  WORDS_CONSUMER_GROUP,
  URLS_CONSUMER_GROUP,
  KAFKA_WORDS_TOPIC,
  KAFKA_HTMLS_TOPIC,
  KAFKA_URLS_TOPIC,
  NUMBER_OF_PARTITIONS_HTMLS,
  NUMBER_OF_PARTITIONS_WORDS,
  NUMBER_OF_PARTITIONS_URLS,
  REDIS_SERVER_HOST,
  REDIS_SERVER_PORT,
  KAFKA_BROKER_HOST,
  KAFKA_BROKER_PORT,
  KAFKA_BROKER_URL,
  KAFKA_PERSIST_DB_TOPIC,
  PERSIST_DB_CONSUMER_GROUP,
  NUMBER_OF_PARTITIONS_PERSIST_DB,
  MONGODB_DATABASE,
  MONGODB_HOST,
  MONGODB_PORT,
  LIMIT_URLS_NUMBER,
};
